import { Ubuntu } from "@next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Provider from "../components/provider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const ubuntu = Ubuntu({
   subsets: ["latin"],
   weight: ["400"],
   style: ["normal", "italic"],
});

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={ubuntu.className}>
         <Provider>
            <body className=" m-0 p-0 overflow-auto">
               {children}
               <ToastContainer/>
            </body>
         </Provider>
      </html>
   );
}
